version: "3.9"
services:
  mysql:
    container_name: mysql-server
    image: mysql/mysql-server:8.0.23
    restart: always
    command: [ --lower_case_table_names=2 ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Test@1234!
      MYSQL_DATABASE: Examples
      MYSQL_ROOT_HOST: "%"